language: java
sudo: required

env:
  global:
    - MAVEN_OPTS="-Xmx512M"
    - MAVEN_SKIP_CHECKS_AND_DOCS="-Dair.check.skip-all=true -Dmaven.javadoc.skip=true"



services:
  - docker

before_install:
  - sudo apt-get install maven
  - mvn -version
  - docker info
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - git submodule update --init

install:
  - mkdir presto; cd presto
  - mvnw install -DskipTests $MAVEN_SKIP_CHECKS_AND_DOCS -B -q -T C1 -pl presto-server
  - cp presto-server/target/presto-server-0.192-SNAPSHOT.tar.gz ../presto-base

script:
  - cd ..
  - make

#after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
#    docker push oleggorj/presto-base:latest;
#    docker push oleggorj/presto-coordinator:latest;
#    docker push oleggorj/presto-worker:latest;
#    fi
    
    
